// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB35Ua_xn1nEOAAW0M21sEnJouSy_WVVr4',
    appId: '1:645488134702:web:7bc8390f673ae919042dbf',
    messagingSenderId: '645488134702',
    projectId: 'uberapp-db564',
    authDomain: 'uberapp-db564.firebaseapp.com',
    databaseURL: 'https://uberapp-db564-default-rtdb.firebaseio.com',
    storageBucket: 'uberapp-db564.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPjlJyCsIqeIlLCabUaqiYf3oVe__mSsg',
    appId: '1:645488134702:android:a8fcd221ead8199f042dbf',
    messagingSenderId: '645488134702',
    projectId: 'uberapp-db564',
    databaseURL: 'https://uberapp-db564-default-rtdb.firebaseio.com',
    storageBucket: 'uberapp-db564.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDN-Ziq7P37DnPsWsOxWW4skClxzilTqJQ',
    appId: '1:645488134702:ios:7fa1f450a2fafd6f042dbf',
    messagingSenderId: '645488134702',
    projectId: 'uberapp-db564',
    databaseURL: 'https://uberapp-db564-default-rtdb.firebaseio.com',
    storageBucket: 'uberapp-db564.appspot.com',
    iosBundleId: 'com.example.usersApp',
  );
}
